### ISSUE TITLE
Recent Sphinx breaks theme?

### ISSUE THREAD

**Issue by masaccio** [danirus/sphinx-nefertiti#29]
I think that a recent Sphinx update may have changed some attributes you rely upon:

``` bash
% poetry run sphinx-build -b html -t HtmlDocs docs docs/build
Running Sphinx v7.3.7
'Theme' object has no attribute 'config'
```

I nuked my config to just contain this:

``` python
html_theme = "sphinx_nefertiti"
```

And the error remains.

**Comment by danirus** [comment]
Previous version of sphinx-nefertiti, v0.3.2, had an issue that displayed that way, but I fixed it in v0.3.3. I am using Sphinx 7.3.7 and sphinx-nefertiti 0.3.3 in other projects and it doesn't have any problem.

Is your repository publicly available? 
I could take a look and debug the problem.

**Comment by masaccio** [comment]
Sure here it is - https://github.com/masaccio/numbers-parser

**Comment by danirus** [comment]
Thanks. I cloned the repo, and updated the version for `sphinx-nefertiti` in the group `tool.poetry.group.docs.dependencies` in the `pyproject.toml` file, to: `sphinx-nefertiti = "^0.3.3"`.
Then I run:

    poetry run sphinx-build -b html -t HtmlDocs docs docs/build

And this is the output:

```text
Running Sphinx v7.3.7
making output directory... done
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 17 source files that are out of date
updating environment: [new config] 17 added, 0 changed, 0 removed
reading sources... [100%] styles
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [100%] styles
generating indices... genindex done
highlighting module code... [100%] numbers_parser.document
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.
```

And the docs look good :-)

Thanks for sharing. I see that many themes fail to build in sphinx-themes.org, and I wonder whether it is not up-to-date on their end or what whether something is wrong in sphinx-nefertiti. 

In this case it's just that the version you were using had issues. 
It is safe for your project to update sphinx-nefertiti to 0.3.3.

**Comment by masaccio** [comment]
Thanks for the debug. Not the first time I’ve fallen foul of poetry’s default version specs being overly precise.
