### ISSUE TITLE
support sphinx 8.x

### ISSUE THREAD

**Issue by zliu** [danirus/sphinx-nefertiti#38]
Hi, 

I have a project that include a few different themes, some of them depend on sphinx 8.x to work, including sphinx-rtd-theme, which has just released its 3.x version that builds with sphinx 8.x.  

However, when I install the nefertiti theme, it will downgrade my sphinx back to 7.x. So I'm wondering, is there any plan to upgrade nefertiti to make it work with sphinx 8.x ?

Thanks.

**Comment by danirus** [comment]
Hi @zliu, thanks for your message. 

I will make a release to remove that constraint. It is an unintentional constrain, Nefertiti for Sphinx works with Sphinx 8. :-)

I am in the process of implementing other changes (back-to-top button, customizable header links, breadcrumbs, etc.) that will be part of a subsequent release, I hope I will have that one in one or two weeks.

**Comment by danirus** [comment]
It is done. Release [0.4.2](https://pypi.org/project/sphinx-nefertiti/) works with Sphinx 8. Thanks again for telling.
If your project is publicly available, please, share the link, I would like to see it :-)

**Comment by zliu** [comment]
@danirus  Thanks for the quick update, it is really fast. 

My project is pulling these public packages through company proxy, so we can use the up-to-date features. However my project is not public, I'm building an internal document hosting site using several different themes for work purpose. It is within our company private network, sorry for not able to share it.
